In [10]:
import pandas as pd
import sklearn
import numpy as np

In [11]:
data=pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")

In [12]:
data.head(5)

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [13]:
for col in data.columns:
    if len(data[col].unique()) <10 and col!='Churn' :
        data=pd.get_dummies(data, columns=[col], dtype=int)
data=data[data["TotalCharges"]!=" "]
data["TotalCharges"]=pd.to_numeric(data["TotalCharges"],errors='coerce')
data.replace({"Churn":{"Yes":1,"No":0}},inplace=True)

customerID  tenure  MonthlyCharges  TotalCharges Churn  gender_Female  \
0     7590-VHVEG       1           29.85         29.85     0              1   
1     5575-GNVDE      34           56.95       1889.50     0              0   
2     3668-QPYBK       2           53.85        108.15     1              0   
3     7795-CFOCW      45           42.30       1840.75     0              0   
4     9237-HQITU       2           70.70        151.65     1              1   
...          ...     ...             ...           ...   ...            ...   
7038  6840-RESVB      24           84.80       1990.50     0              0   
7039  2234-XADUH      72          103.20       7362.90     0              1   
7040  4801-JZAZL      11           29.60        346.45     0              1   
7041  8361-LTMKD       4           74.40        306.60     1              0   
7042  3186-AJIEK      66          105.65       6844.50     0              0   

      gender_Male  SeniorCitizen_0  SeniorCitizen_1  Partner_No  ...  \
0               0                1                0           0  ...   
1               1                1                0           1  ...   
2               1                1                0           1  ...   
3               1                1                0           1  ...   
4               0                1                0           1  ...   
...           ...              ...              ...         ...  ...   
7038            1                1                0           0  ...   
7039            0                1                0           0  ...   
7040            0                1                0           0  ...   
7041            1                0                1           0  ...   
7042            1                1                0           1  ...   

      StreamingMovies_Yes  Contract_Month-to-month  Contract_One year  \
0                       0                        1                  0   
1                       0                        0                  1   
2                       0                        1                  0   
3                       0                        0                  1   
4                       0                        1                  0   
...                   ...                      ...                ...   
7038                    1                        0                  1   
7039                    1                        0                  1   
7040                    0                        1                  0   
7041                    0                        1                  0   
7042                    1                        0                  0   

      Contract_Two year  PaperlessBilling_No  PaperlessBilling_Yes  \
0                     0                    0                     1   
1                     0                    1                     0   
2                     0                    0                     1   
3                     0                    1                     0   
4                     0                    0                     1   
...                 ...                  ...                   ...   
7038                  0                    0                     1   
7039                  0                    0                     1   
7040                  0                    0                     1   
7041                  0                    0                     1   
7042                  1                    0                     1   

      PaymentMethod_Bank transfer (automatic)  \
0                                           0   
1                                           0   
2                                           0   
3                                           1   
4                                           0   
...                                       ...   
7038                                        0   
7039                                        0   
7040                             

In [14]:
X = data.drop(columns=["customerID","Churn"])
y = data["Churn"]

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.05, random_state=42)

In [16]:
#dataframe to numpy array
X_np = X_train.to_numpy()
Data_y = y_train.to_numpy()
#transpose of X
Data_X = X_np.T
#stacking a row of ones
row_1=np.ones((1,Data_X.shape[1]))
Data_X=np.vstack((row_1,Data_X))


In [17]:
Data_X

array([[ 1.  ,  1.  ,  1.  , ...,  1.  ,  1.  ,  1.  ],
       [ 1.  , 16.  , 34.  , ...,  9.  , 50.  , 20.  ],
       [44.15, 68.25, 65.  , ..., 81.15, 19.75, 73.65],
       ...,
       [ 0.  ,  0.  ,  0.  , ...,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  , ...,  1.  ,  0.  ,  1.  ],
       [ 0.  ,  0.  ,  1.  , ...,  0.  ,  0.  ,  0.  ]], shape=(47, 6680))

In [18]:
Data_X.shape

(47, 6680)

In [19]:
#sigmoid function
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [20]:
#creating the thetas
theta=np.zeros((Data_X.shape[0],1))

In [21]:
#h_theta function
def h_theta(theta,Data_X):
    z=np.dot(theta.T,Data_X)
    return sigmoid(z)
h_theta(theta,Data_X)


array([[0.5, 0.5, 0.5, ..., 0.5, 0.5, 0.5]], shape=(1, 6680))

In [22]:
#gradient function
def gradient(theta,Data_X,Data_y):
    grad=(1/Data_X.shape[1])*np.dot((Data_y - h_theta(theta,Data_X)), Data_X.T)
    return grad

In [23]:
gradient(theta,Data_X,Data_y)

array([[-0.2338323353293413, -11.400523952095808, -12.59814371257486,
        -734.6848914670652, -0.11287425149700599, -0.12095808383233533,
        -0.22073353293413173, -0.01309880239520958, -0.0874251497005988,
        -0.14640718562874253, -0.13023952095808383, -0.10359281437125749,
        -0.024101796407185627, -0.20973053892215568,
        -0.12043413173652695, -0.024101796407185627,
        -0.08929640718562874, -0.10651197604790419,
        -0.035404191616766466, -0.09191616766467066,
        -0.03997005988023952, -0.09191616766467066, -0.10194610778443114,
        -0.04341317365269461, -0.09191616766467066, -0.09850299401197604,
        -0.04790419161676647, -0.09191616766467066, -0.09401197604790419,
        -0.04124251497005988, -0.09191616766467066, -0.10067365269461077,
        -0.06519461077844312, -0.09191616766467066, -0.07672155688622755,
        -0.06362275449101797, -0.09191616766467066, -0.0782934131736527,
        -0.04094311377245509, -0.08053892215568863, -0.11

In [24]:
#gradient descent function
def gradient_descent(theta,Data_X,Data_y,learning_rate,num_iterations):
    for i in range(num_iterations):
        grad=gradient(theta,Data_X,Data_y)
        theta=theta + learning_rate*grad.T
    return theta

In [25]:
theta_opt=gradient_descent(theta,Data_X,Data_y,0.01,1000)

TypeError: loop of ufunc does not support argument 0 of type float which has no callable exp method

In [ ]:
y_test.shape

In [ ]:
X_test.shape

In [113]:
#dataframe to numpy array
X_test_np = X_test.to_numpy()
Y_test_np = y_test.to_numpy()
#transpose of X
X_test_1 = X_test_np.T
row_1=np.ones((1,X_test_1.shape[1]))
X_test_1=np.vstack((row_1,X_test_1))

In [ ]:
X_test_1

In [ ]:
X_test_1.T[1]

In [ ]:
y_pred=h_theta(theta_opt,X_test_1)

In [ ]:
y_pred

In [118]:
y_p=np.where(y_pred>=0.5,1,0)

In [ ]:
y_p

In [120]:
#compare y_pred with y_test
matches= y_p == Y_test_np

In [123]:
#true positive estimation
TP_plus_TN=np.sum(matches)

In [ ]:
Accuracy=TP_plus_TN/Y_test_np.shape[0]
Accuracy   