In [44]:
import pandas as pd
import sklearn
import numpy as np

In [45]:
data=pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")

In [46]:
data.head(5)

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [47]:
for col in data.columns:
    if len(data[col].unique()) <10 and col!='Churn' :
        data=pd.get_dummies(data, columns=[col], dtype=int)
data=data[data["TotalCharges"]!=" "]
data["TotalCharges"]=pd.to_numeric(data["TotalCharges"],errors='coerce')
data.replace({"Churn":{"Yes":1,"No":0}},inplace=True)

customerID  tenure  MonthlyCharges  TotalCharges Churn  gender_Female  \
0     7590-VHVEG       1           29.85         29.85     0              1   
1     5575-GNVDE      34           56.95       1889.50     0              0   
2     3668-QPYBK       2           53.85        108.15     1              0   
3     7795-CFOCW      45           42.30       1840.75     0              0   
4     9237-HQITU       2           70.70        151.65     1              1   
...          ...     ...             ...           ...   ...            ...   
7038  6840-RESVB      24           84.80       1990.50     0              0   
7039  2234-XADUH      72          103.20       7362.90     0              1   
7040  4801-JZAZL      11           29.60        346.45     0              1   
7041  8361-LTMKD       4           74.40        306.60     1              0   
7042  3186-AJIEK      66          105.65       6844.50     0              0   

      gender_Male  SeniorCitizen_0  SeniorCitizen_1  Partner_No  ...  \
0               0                1                0           0  ...   
1               1                1                0           1  ...   
2               1                1                0           1  ...   
3               1                1                0           1  ...   
4               0                1                0           1  ...   
...           ...              ...              ...         ...  ...   
7038            1                1                0           0  ...   
7039            0                1                0           0  ...   
7040            0                1                0           0  ...   
7041            1                0                1           0  ...   
7042            1                1                0           1  ...   

      StreamingMovies_Yes  Contract_Month-to-month  Contract_One year  \
0                       0                        1                  0   
1                       0                        0                  1   
2                       0                        1                  0   
3                       0                        0                  1   
4                       0                        1                  0   
...                   ...                      ...                ...   
7038                    1                        0                  1   
7039                    1                        0                  1   
7040                    0                        1                  0   
7041                    0                        1                  0   
7042                    1                        0                  0   

      Contract_Two year  PaperlessBilling_No  PaperlessBilling_Yes  \
0                     0                    0                     1   
1                     0                    1                     0   
2                     0                    0                     1   
3                     0                    1                     0   
4                     0                    0                     1   
...                 ...                  ...                   ...   
7038                  0                    0                     1   
7039                  0                    0                     1   
7040                  0                    0                     1   
7041                  0                    0                     1   
7042                  1                    0                     1   

      PaymentMethod_Bank transfer (automatic)  \
0                                           0   
1                                           0   
2                                           0   
3                                           1   
4                                           0   
...                                       ...   
7038                                        0   
7039                                        0   
7040                             

In [48]:
X = data.drop(columns=["customerID","Churn"])
y = data["Churn"]

In [49]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.05, random_state=42)

In [50]:
#dataframe to numpy array
X_np = X_train.to_numpy()
Data_y = y_train.to_numpy()
#transpose of X
Data_X = X_np.T
#stacking a row of ones
row_1=np.ones((1,Data_X.shape[1]))
Data_X=np.vstack((row_1,Data_X))


In [51]:
Data_X

array([[ 1.  ,  1.  ,  1.  , ...,  1.  ,  1.  ,  1.  ],
       [ 1.  , 16.  , 34.  , ...,  9.  , 50.  , 20.  ],
       [44.15, 68.25, 65.  , ..., 81.15, 19.75, 73.65],
       ...,
       [ 0.  ,  0.  ,  0.  , ...,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  , ...,  1.  ,  0.  ,  1.  ],
       [ 0.  ,  0.  ,  1.  , ...,  0.  ,  0.  ,  0.  ]], shape=(47, 6680))

In [52]:
Data_X.shape

(47, 6680)

In [53]:
#sigmoid function
def sigmoid(z):
    return 1.0 / (1.0 + z)

In [54]:
#creating the thetas
theta=np.zeros((Data_X.shape[0],1))

In [55]:
#h_theta function
def h_theta(theta,Data_X):
    z=np.dot(theta.T,Data_X)
    return sigmoid(z)
h_theta(theta,Data_X)


array([[1., 1., 1., ..., 1., 1., 1.]], shape=(1, 6680))

In [56]:
#gradient function
def gradient(theta,Data_X,Data_y):
    grad=(1/Data_X.shape[1])*np.dot((Data_y - h_theta(theta,Data_X)), Data_X.T)
    return grad

In [57]:
gradient(theta,Data_X,Data_y)

array([[-0.7338323353293413, -27.58817365269461, -45.03053892215568,
        -1878.447410179637, -0.36002994011976047, -0.3738023952095808,
        -0.6398203592814371, -0.09401197604790419, -0.3465568862275449,
        -0.3872754491017964, -0.4808383233532934, -0.25299401197604793,
        -0.07245508982035928, -0.661377245508982, -0.36137724550898204,
        -0.07245508982035928, -0.3, -0.2778443113772455,
        -0.2559880239520958, -0.2, -0.2880239520958084, -0.2,
        -0.24580838323353293, -0.262125748502994, -0.2,
        -0.2717065868263473, -0.26721556886227543, -0.2,
        -0.2666167664670659, -0.2880239520958084, -0.2,
        -0.24580838323353293, -0.26407185628742513, -0.2,
        -0.2697604790419162, -0.26062874251497004, -0.2,
        -0.27320359281437123, -0.3175149700598802, -0.18458083832335329,
        -0.23173652694610777, -0.337874251497006, -0.39595808383233533,
        -0.17979041916167665, -0.18353293413173652, -0.18547904191616765,
        -0.18502994011

In [58]:
#gradient descent function
def gradient_descent(theta,Data_X,Data_y,learning_rate,num_iterations):
    for i in range(num_iterations):
        grad=gradient(theta,Data_X,Data_y)
        theta=theta + learning_rate*grad.T
    return theta

In [59]:
theta_opt=gradient_descent(theta,Data_X,Data_y,0.01,1000)

In [60]:
y_test.shape

(352,)

In [61]:
X_test.shape

(352, 46)

In [62]:
#dataframe to numpy array
X_test_np = X_test.to_numpy()
Y_test_np = y_test.to_numpy()
#transpose of X
X_test_1 = X_test_np.T
row_1=np.ones((1,X_test_1.shape[1]))
X_test_1=np.vstack((row_1,X_test_1))

In [63]:
X_test_1

array([[  1.  ,   1.  ,   1.  , ...,   1.  ,   1.  ,   1.  ],
       [ 61.  ,  19.  ,  13.  , ...,  54.  ,  72.  ,   1.  ],
       [ 25.  ,  24.7 , 102.25, ..., 110.45,  24.1 ,  79.35],
       ...,
       [  0.  ,   0.  ,   1.  , ...,   0.  ,   1.  ,   0.  ],
       [  0.  ,   0.  ,   0.  , ...,   1.  ,   0.  ,   1.  ],
       [  0.  ,   0.  ,   0.  , ...,   0.  ,   0.  ,   0.  ]],
      shape=(47, 352))

In [64]:
X_test_1.T[1]

array([  1.  ,  19.  ,  24.7 , 465.85,   1.  ,   0.  ,   1.  ,   0.  ,
         1.  ,   0.  ,   1.  ,   0.  ,   0.  ,   1.  ,   0.  ,   0.  ,
         1.  ,   0.  ,   0.  ,   1.  ,   0.  ,   1.  ,   0.  ,   0.  ,
         1.  ,   0.  ,   0.  ,   1.  ,   0.  ,   0.  ,   1.  ,   0.  ,
         0.  ,   1.  ,   0.  ,   0.  ,   1.  ,   0.  ,   1.  ,   0.  ,
         0.  ,   1.  ,   0.  ,   1.  ,   0.  ,   0.  ,   0.  ])

In [65]:
y_pred=h_theta(theta_opt,X_test_1)

In [66]:
y_pred

array([[1.634840214309416e-07, 5.260858985828562e-07,
        1.8020878802513633e-07, 1.2086738891291586e-07,
        1.5085424064123531e-06, 2.563667946863151e-06,
        6.01915598077253e-08, 1.7497524415951052e-07,
        1.3628802063387367e-07, 4.4347092934082354e-08,
        7.87062347603407e-07, 3.86099694386005e-07,
        2.496996519476007e-07, 3.5269613182388716e-07,
        3.3489726664710266e-08, 1.1369899750880673e-07,
        2.5054921602318976e-06, 7.533001866017451e-08,
        1.2253966467279664e-07, 4.134284710755444e-08,
        2.6137180712987144e-07, 1.7245394623881833e-07,
        9.281379603762014e-07, 5.37887364023602e-08,
        1.931993974953173e-06, 1.1141619905941987e-07,
        2.969872974979791e-07, 6.800613678374956e-07,
        5.191520718329904e-07, 3.33449084295773e-07,
        5.381306240089845e-08, 3.3722527529037566e-06,
        7.712735571830107e-08, 3.512873759658162e-08,
        1.4967817355829373e-06, 1.0789567657741694e-06,
        1.459580

In [67]:
y_p=np.where(y_pred>=0.5,1,0)

In [68]:
y_p

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [69]:
#compare y_pred with y_test
matches= y_p == Y_test_np

In [70]:
#true positive estimation
TP_plus_TN=np.sum(matches)

In [71]:
Accuracy=TP_plus_TN/Y_test_np.shape[0]
Accuracy   

np.float64(0.7414772727272727)