In [94]:
import pandas as pd
import sklearn
import numpy as np

In [95]:
data=pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")

In [96]:
data.head(5)

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [97]:
for col in data.columns:
    if len(data[col].unique()) <10 and col!='Churn' :
        data=pd.get_dummies(data, columns=[col], dtype=int)
data=data[data["TotalCharges"]!=" "]
data["TotalCharges"]=pd.to_numeric(data["TotalCharges"],errors='coerce')
data.replace({"Churn":{"Yes":1,"No":0}},inplace=True)

/var/folders/8k/h46z50qn34jffkbyc2x9126h0000gn/T/ipykernel_57430/2465667453.py:6: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data.replace({"Churn":{"Yes":1,"No":0}},inplace=True)


In [98]:
X = data.drop(columns=["customerID","Churn"])
y = data["Churn"]

In [99]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.05, random_state=42)

In [100]:
#dataframe to numpy array
X_np = X_train.to_numpy()
Data_y = y_train.to_numpy()
#transpose of X
Data_X = X_np.T
#stacking a row of ones
row_1=np.ones((1,Data_X.shape[1]))
Data_X=np.vstack((row_1,Data_X))


In [101]:
Data_X

array([[ 1.  ,  1.  ,  1.  , ...,  1.  ,  1.  ,  1.  ],
       [ 1.  , 16.  , 34.  , ...,  9.  , 50.  , 20.  ],
       [44.15, 68.25, 65.  , ..., 81.15, 19.75, 73.65],
       ...,
       [ 0.  ,  0.  ,  0.  , ...,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  , ...,  1.  ,  0.  ,  1.  ],
       [ 0.  ,  0.  ,  1.  , ...,  0.  ,  0.  ,  0.  ]], shape=(47, 6680))

In [102]:
Data_X.shape

(47, 6680)

In [103]:
#sigmoid function
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [104]:
#creating the thetas
theta=np.zeros((Data_X.shape[0],1))

In [105]:
#h_theta function
def h_theta(theta,Data_X):
    z=np.dot(theta.T,Data_X)
    return sigmoid(z)
h_theta(theta,Data_X)


array([[0.5, 0.5, 0.5, ..., 0.5, 0.5, 0.5]], shape=(1, 6680))

In [106]:
#gradient function
def gradient(theta,Data_X,Data_y):
    grad=(1/Data_X.shape[1])*np.dot((Data_y - h_theta(theta,Data_X)), Data_X.T)
    return grad

In [107]:
gradient(theta,Data_X,Data_y)

array([[-2.33832335e-01, -1.14005240e+01, -1.25981437e+01,
        -7.34684891e+02, -1.12874251e-01, -1.20958084e-01,
        -2.20733533e-01, -1.30988024e-02, -8.74251497e-02,
        -1.46407186e-01, -1.30239521e-01, -1.03592814e-01,
        -2.41017964e-02, -2.09730539e-01, -1.20434132e-01,
        -2.41017964e-02, -8.92964072e-02, -1.06511976e-01,
        -3.54041916e-02, -9.19161677e-02, -3.99700599e-02,
        -9.19161677e-02, -1.01946108e-01, -4.34131737e-02,
        -9.19161677e-02, -9.85029940e-02, -4.79041916e-02,
        -9.19161677e-02, -9.40119760e-02, -4.12425150e-02,
        -9.19161677e-02, -1.00673653e-01, -6.51946108e-02,
        -9.19161677e-02, -7.67215569e-02, -6.36227545e-02,
        -9.19161677e-02, -7.82934132e-02, -4.09431138e-02,
        -8.05389222e-02, -1.12350299e-01, -1.35628743e-01,
        -9.82035928e-02, -7.14071856e-02, -7.56736527e-02,
        -1.63922156e-02, -7.03592814e-02]])

In [108]:
#gradient descent function
def gradient_descent(theta,Data_X,Data_y,learning_rate,num_iterations):
    for i in range(num_iterations):
        grad=gradient(theta,Data_X,Data_y)
        theta=theta + learning_rate*grad.T
    return theta

In [109]:
theta_opt=gradient_descent(theta,Data_X,Data_y,0.01,1000)

/var/folders/8k/h46z50qn34jffkbyc2x9126h0000gn/T/ipykernel_57430/3474394088.py:3: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))


In [111]:
y_test.shape

(352,)

In [112]:
X_test.shape

(352, 46)

In [113]:
#dataframe to numpy array
X_test_np = X_test.to_numpy()
Y_test_np = y_test.to_numpy()
#transpose of X
X_test_1 = X_test_np.T
row_1=np.ones((1,X_test_1.shape[1]))
X_test_1=np.vstack((row_1,X_test_1))

In [114]:
X_test_1

array([[  1.  ,   1.  ,   1.  , ...,   1.  ,   1.  ,   1.  ],
       [ 61.  ,  19.  ,  13.  , ...,  54.  ,  72.  ,   1.  ],
       [ 25.  ,  24.7 , 102.25, ..., 110.45,  24.1 ,  79.35],
       ...,
       [  0.  ,   0.  ,   1.  , ...,   0.  ,   1.  ,   0.  ],
       [  0.  ,   0.  ,   0.  , ...,   1.  ,   0.  ,   1.  ],
       [  0.  ,   0.  ,   0.  , ...,   0.  ,   0.  ,   0.  ]],
      shape=(47, 352))

In [115]:
X_test_1.T[1]

array([  1.  ,  19.  ,  24.7 , 465.85,   1.  ,   0.  ,   1.  ,   0.  ,
         1.  ,   0.  ,   1.  ,   0.  ,   0.  ,   1.  ,   0.  ,   0.  ,
         1.  ,   0.  ,   0.  ,   1.  ,   0.  ,   1.  ,   0.  ,   0.  ,
         1.  ,   0.  ,   0.  ,   1.  ,   0.  ,   0.  ,   1.  ,   0.  ,
         0.  ,   1.  ,   0.  ,   0.  ,   1.  ,   0.  ,   1.  ,   0.  ,
         0.  ,   1.  ,   0.  ,   1.  ,   0.  ,   0.  ,   0.  ])

In [116]:
y_pred=h_theta(theta_opt,X_test_1)

/var/folders/8k/h46z50qn34jffkbyc2x9126h0000gn/T/ipykernel_57430/3474394088.py:3: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))


In [117]:
y_pred

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 2.50198117e-061, 1.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 1.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 1.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 2.68221979e-035, 0.00000000e+000,
        1.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 1.97159593e-249, 0.00000000e+000,
        0.00000000e+000, 1.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 7.53067546e-211, 4.05781177e-298,
        0.00000000e+000, 1.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 1.00000000e+000, 0.00000000e+000,
        7.52092168e-069, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        1.00000000e+000, 0.00000000e+000, 0.00000000e+00

In [118]:
y_p=np.where(y_pred>=0.5,1,0)

In [119]:
y_p

array([[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 

In [120]:
#compare y_pred with y_test
matches= y_p == Y_test_np

In [123]:
#true positive estimation
TP_plus_TN=np.sum(matches)

In [125]:
Accuracy=TP_plus_TN/Y_test_np.shape[0]
Accuracy   

np.float64(0.7840909090909091)